language: java
jdk:
  - oraclejdk8
sudo: false
script: mvn clean verify
install:
  - "cd Services"
  - "mvn spring-boot:run -Dspring.profiles.active=prod" 
env:
  - NODE_ENV=travis
deploy:
  provider: openshift
  user: marianogvarela@gmail.com
  password: s2BePq54dA
  domain: vymaster
  app: arqapi
